### ISSUE TITLE
Some Advanced chrome extension Issues !!

### ISSUE THREAD

**Issue by larajeanz1999** [circles-png/baulkowebapp#21]
Hi everyone

I want to make an extension chrome that is like ''like4like'' website about exchanging likes and shares... but I want that extension to do 
those tasks automatically ...like, share ,comment.... like Everve extension's, that extension performe tasks automatically, the extension should includ login and admin panel and ... complete website but in extension ..users can add campaigns and earn credits just from the extension ..

In fact I know the basics but runing them automatically it's complicated for me  

I will appreciate any help even just idea !!

Thanks

**Comment by circles-png** [comment]
what

**Comment by larajeanz1999** [comment]
Sorry I made mistake !!
