### ISSUE TITLE
Wrong Bell times

### ISSUE THREAD

**Issue by NikhilJathan** [circles-png/baulkowebapp#9]
The bell times displayed on the site have not been updated yet for the new bell times. I have attached the new bell times below
[Bell Times Term 1 2022.pdf](https://github.com/ML-10/baulkowebapp/files/8056981/Bell.Times.Term.1.2022.pdf)
.

**Comment by ML-10** [comment]
ok

**Comment by aaaaalan2022** [comment]
ok bro coolio

**Comment by aaaaalan2022** [comment]
fix it

**Comment by ML-10** [comment]
@NikhilJathan fixed (i think) (comment if its not right)

**Comment by ML-10** [comment]
nvm not fixed

**Comment by aaaaalan2022** [comment]
yes
still broken
thank you for doing it tho
gl

**Comment by NikhilJathan** [comment]
I may try to see if I can figure out how to fix it myself if I get the time

**Comment by ML-10** [comment]
ive just gotta convert hours and minutes to minutes
i dont have the time

**Comment by aaaaalan2022** [comment]
nice pun
however
your mother

**Comment by ML-10** [comment]
wait i didnt even realise i made a joke

**Comment by circles-png** [comment]
#12 haha

should be fixed now

**Comment by aaaaalan2022** [comment]
fixed?

**Comment by aaaaalan2022** [comment]
lemme check wait

**Comment by aaaaalan2022** [comment]
yeah its fixed nvm

**Comment by aaaaalan2022** [comment]
no it isnt matthew you broke it again
